# Generated by Django 5.0.6 on 2024-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stockdata_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
