# Generated by Django 5.0.6 on 2024-06-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_stockdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.CharField(max_length=100),
        ),
    ]
